### ISSUE TITLE
disagreement with SQL on particular date

### ISSUE THREAD

**Issue by trespitt** [chiefmurph/mondate#3]
I've been using this awesome package to replicate pl sql's months between function. For all but one date I've tested, the outputs are the same up to 5 decimal points (the precision of sql is much greater). Here's the example:

`get.mb('10-25-2017','04-23-2014')
[1] 42.03978`

`SELECT MONTHS_BETWEEN 
   (TO_DATE('10-25-2017','MM-DD-YYYY'),
    TO_DATE('04-23-2014','MM-DD-YYYY') ) "Months"
    FROM DUAL;
42.06451612903225806451612903225806451613`

I'm not sure if this is a bug - it could just be a different definition of month. thanks for the great work!

**Comment by chiefmurph** [comment]
I'm not exactly sure what your function get.mb does, but I assume it's something like
get.md <- function(x, y) mondate(x) - mondate(y)

"it could just be a different definition of month" -- Yes. mondate is based on fractional months where the fraction depends on the number of days in a month. So mondate's calculation is equivalent to
> 7/30 + 8 + 12 + 12 + 9 + 25/31
[1] 42.03978
(seven days in April remaining after the end of business on 4-23-2014 + 8 months remaining in 2014 + 12 months for 2015 and 2016 + 9 months in 2017 through the end of September, plus 25 days in October).
Per https://www.techonthenet.com/oracle/functions/months_between.php, the "MONTHS_BETWEEN function calculates the fraction based on a 31-day month". April 2014 has 30 days, which I suspect is the primary reason behind the difference. I don't know the complete algorithm behind MONTHS_BETWEEN, but it's not as simple as replacing 30 with 31 in the fraction for April 2014 because you would get a smaller number, whereas your number is greater. So, "a different definition of month" is the best answer I can give you.

"thanks for the great work!" Thank you!

**Comment by chiefmurph** [comment]
No followup in over a year. Assume issue is closed.
